import { NgModule } from '@angular/core';
import {
  MatAutocompleteModule, MatButtonModule, MatCardModule, MatCheckboxModule, MatChipsModule, MatDatepickerModule,
  MatDialogModule, MatDividerModule, MatExpansionModule, MatFormFieldModule, MatGridListModule, MatIconModule, MatInputModule,
  MatListModule, MatMenuModule, MatNativeDateModule, MatPaginatorModule, MatProgressBarModule, MatProgressSpinnerModule, MatSelectModule,
  MatSidenavModule, MatSlideToggleModule, MatSnackBarModule, MatSortModule, MatStepperModule, MatTableModule, MatTabsModule,
  MatToolbarModule, MatTooltipModule
} from '@angular/material';

@NgModule({
  imports: [
      MatButtonModule,
      MatCheckboxModule,
      MatTableModule,
      MatCardModule,
      MatDatepickerModule,
      MatAutocompleteModule,
      MatMenuModule,
      MatSidenavModule,
      MatToolbarModule,
      MatIconModule,
      MatListModule,
      MatFormFieldModule,
      MatInputModule,
      MatTabsModule,
      MatTooltipModule,
      MatStepperModule,
      MatDialogModule,
      MatSnackBarModule,
      MatGridListModule,
      MatNativeDateModule,
      MatSelectModule,
      MatPaginatorModule,
      MatProgressBarModule,
      MatProgressSpinnerModule,
      MatExpansionModule,
      MatSortModule,
      MatChipsModule,
      MatSlideToggleModule,
      MatDividerModule
  ],
  exports: [
      MatButtonModule,
      MatCheckboxModule,
      MatTableModule,
      MatCardModule,
      MatDatepickerModule,
      MatAutocompleteModule,
      MatMenuModule,
      MatSidenavModule,
      MatToolbarModule,
      MatIconModule,
      MatListModule,
      MatFormFieldModule,
      MatInputModule,
      MatTabsModule,
      MatTooltipModule,
      MatStepperModule,
      MatDialogModule,
      MatSnackBarModule,
      MatGridListModule,
      MatNativeDateModule,
      MatSelectModule,
      MatPaginatorModule,
      MatProgressBarModule,
      MatProgressSpinnerModule,
      MatExpansionModule,
      MatSortModule,
      MatChipsModule,
      MatSlideToggleModule,
      MatDividerModule
  ]
})
export class UiuxModule { }
